---
name: Assignment
break: true
fastfail: false
indent: 4
version: v1.1.0
startup: poetry install
---

# check the technical writing for various characteristics
- writing/reflection.md:
    - description: Ensure that reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Write a minimum number of meaningful words (100) in the reflection
      check: CountFileWords
      options:
        count: 100
        exact: false
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 8
        exact: true
    - description: Complete all TODOs, remove the TODO markers in the reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true

- pyproject.toml:
  - description: 'Add pytest as a development dependency'
    check: MatchFileFragment
    options:
      fragment: pytest
      count: 2
      exact: false

# run the program and confirm the existence of fragments in its output
- description: 'Fix all bugs in tests/test_area.py'
  check: MatchCommandFragment
  options:
    command: 'poetry run pytest tests/test_area.py'
    fragment: 14 passed
    count: 1
    exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (6) in repository
  check: CountCommits
  options:
    count: 1
